version: '3.8'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: flyingrobots-test
    environment:
      - NODE_ENV=test
      - CI=true
    volumes:
      # Mount source code for live updates during development
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
      - ./vite.config.js:/app/vite.config.js:ro
      - ./vitest.config.js:/app/vitest.config.js:ro
      # Mount output directories for test results
      - ./test-results:/app/test-results
      - ./coverage:/app/coverage
    command: npm run test:docker